name: debug

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  set-variables:
    runs-on: ubuntu-latest
    outputs:
      environment_name: ${{ steps.dynamic_variables.outputs.ENVIRONMENT_NAME }}
      environment_url: ${{ steps.dynamic_variables.outputs.ENVIRONMENT_URL }}
    steps:
      - name: Dynamic Variables
        id: dynamic_variables
        run: |
          ENV_NAME=$(date +%s)
          ENV_URL="${ENV_NAME}.nintendo.com"
          echo "ENVIRONMENT_NAME=${ENV_NAME}" >> $GITHUB_ENV
          echo "ENVIRONMENT_URL=${ENV_URL}" >> $GITHUB_ENV
          echo "::set-output name=ENVIRONMENT_NAME::${ENV_NAME}"
          echo "::set-output name=ENVIRONMENT_URL::${ENV_URL}"

  post-url:
    runs-on: ubuntu-latest
    needs: set-variables
    environment:
      name: stage
      url: ${{ needs.set-variables.outputs.environment_url }}
    steps:
      - name: Debug
        run: |
          echo "Environment Name: ${{ needs.set-variables.outputs.environment_name }}"
          echo "Environment URL: ${{ needs.set-variables.outputs.environment_url }}"
