on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    name: forge-action
    steps:
      - name: Get Branch Name
        shell: bash
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo $BRANCH_NAME

      # - uses: anthonyneto/forge-action@dev
      #   with:
      #     GITHUB_BRANCH: ${{ env.GITHUB_BRANCH }}
