on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    name: forge-action
    environment: default
    steps:
      - name: Get Branch Name
        run: |
          GITHUB_BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "GITHUB_BRANCH_NAME=$GITHUB_BRANCH_NAME" >> $GITHUB_ENV
          # Example of setting another variable
          echo "FORGE_SERVER_ID=my-server-id" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: |
          echo "GITHUB_BRANCH_NAME=${{ env.GITHUB_BRANCH_NAME }}"
          echo "FORGE_SERVER_ID=${{ env.FORGE_SERVER_ID }}"
          echo "FORGE_ZONE=${{ env.FORGE_SERVER_ID }}"

      - name: Use Forge Action
        uses: anthonyneto/forge-action@dev
        with:
          GITHUB_BRANCH_NAME: ${{ env.GITHUB_BRANCH_NAME }}
          FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
          FORGE_SERVER_ID: ${{ env.FORGE_SERVER_ID }}
          FORGE_ZONE: ${{ env.FORGE_ZONE }}
          FORGE_GIT_URL: ${{ env.FORGE_GIT_URL }}
