on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment context'
        required: true
        type: choice
        options:
          - default
          - development
          - staging
          - production

jobs:
  main:
    runs-on: ubuntu-latest
    name: forge-action
    environment: ${{ github.event.inputs.environment || 'default' }}
    steps:
      - name: Get Branch Name
        run: |
          GITHUB_BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "GITHUB_BRANCH_NAME=$GITHUB_BRANCH_NAME" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: |
          echo "GITHUB_BRANCH_NAME=${{ vars.GITHUB_BRANCH_NAME }}"
          echo "FORGE_SERVER_ID=${{ vars.FORGE_SERVER_ID }}"
          echo "FORGE_ZONE=${{ vars.FORGE_ZONE }}"
          echo "FORGE_GIT_URL=${{ vars.FORGE_GIT_URL }}"

      - name: Use Forge Action
        uses: anthonyneto/forge-action@dev
        with:
          GITHUB_BRANCH_NAME: ${{ env.GITHUB_BRANCH_NAME }}
          FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
          FORGE_SERVER_ID: ${{ vars.FORGE_SERVER_ID }}
          FORGE_ZONE: ${{ vars.FORGE_ZONE }}
          FORGE_GIT_URL: ${{ vars.FORGE_GIT_URL }}
