on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    name: forge-action
    steps:
      - name: Get Branch Name
        run: |
          GITHUB_BRANCH="${GITHUB_REF#refs/heads/}"
          echo "GITHUB_BRANCH=$GITHUB_BRANCH" >> $GITHUB_ENV

      - name: Use Forge Action
        uses: anthonyneto/forge-action@dev
        with:
          GITHUB_BRANCH: ${{ env.GITHUB_BRANCH }}
