name: Send PR Message

on:
  pull_request:
    types: [opened, edited]

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to pull request
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          MESSAGE="Thank you for your contribution! We will review it soon."
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\":\"$MESSAGE\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments"
